#!/bin/sh
# 	 Copyright 2013 Uniclau S.L. (www.uniclau.com)
# 	
#    This file is part of jbPivot.
#
#    jbPivot is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    jbPivot is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with jbPivot.  If not, see <http://www.gnu.org/licenses/>.

rm build/*
cat src/pivot.js src/group_*.js src/agregate_*.js src/formatter_*.js  > build/jbpivot.js
cat css/*.css > build/jbpivot.css
java -jar ~/git/yuicompressor-2.4.7/build/yuicompressor-2.4.7.jar build/jbPivot.js -o build/jbpivot.min.js
java -jar ~/git/yuicompressor-2.4.7/build/yuicompressor-2.4.7.jar build/jbPivot.css -o build/jbpivot.min.css

